name: expanse_tracker
description: Add daily expanse entries, create ledgers and know your account balance. Expanse Tracker is simple cash management and bookkeeping app for all kind of business.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  pinput: ^2.2.23
  intl: ^0.17.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

